// Harness API v1 公开稳定面——协议层唯一入口（R5 状态所有者）。
// 所有实现（翻译桥 / SDK / 未来投影）从这里 import schema 与版本常量。
// 红线：不 import acode-protocol（v4）；本目录类型独立演进，删改语义必须升主版本。

export {
  HARNESS_API_VERSION_MAJOR,
  HARNESS_API_VERSION_MINOR,
  HARNESS_MAX_LINE_LENGTH,
  harnessHelloFrameSchema,
  harnessHelloAckFrameSchema,
  harnessRequestFrameSchema,
  harnessResponseFrameSchema,
  harnessEventFrameSchema,
  harnessProtocolErrorFrameSchema,
  harnessErrorDetailSchema,
  harnessHelloVersionProbeSchema,
  parseFrameLoose,
  type HarnessHelloFrame,
  type HarnessHelloAckFrame,
  type HarnessRequestFrame,
  type HarnessResponseFrame,
  type HarnessEventFrame,
  type HarnessProtocolErrorFrame,
  type HarnessErrorDetail,
  type HarnessUnknownFrame,
  type HarnessFrame,
} from "./frames.js";

export {
  harnessEventKindSchema,
  harnessEventSchema,
  parseEventLoose,
  textDeltaEventSchema,
  turnStartedEventSchema,
  turnDoneEventSchema,
  toolCallStartedEventSchema,
  toolCallFinishedEventSchema,
  permissionRequestedEventSchema,
  tokenUsageEventSchema,
  harnessErrorEventSchema,
  unknownEventSchema,
  type HarnessEventKind,
  type HarnessEvent,
  type TextDeltaEvent,
  type TurnStartedEvent,
  type TurnDoneEvent,
  type ToolCallStartedEvent,
  type ToolCallFinishedEvent,
  type PermissionRequestedEvent,
  type TokenUsageEvent,
  type HarnessErrorEvent,
  type UnknownEvent,
} from "./events.js";

export {
  HARNESS_METHODS,
  isHarnessMethodName,
  harnessMethodParamsSchemas,
  harnessModelSelectionSchema,
  listSessionsParamsSchema,
  listSessionsResultSchema,
  harnessSessionSummarySchema,
  createSessionParamsSchema,
  createSessionResultSchema,
  attachSessionParamsSchema,
  detachSessionParamsSchema,
  detachSessionResultSchema,
  forkSessionParamsSchema,
  rewindSessionParamsSchema,
  rewindSessionResultSchema,
  sendMessageParamsSchema,
  sendMessageResultSchema,
  cancelTurnParamsSchema,
  cancelTurnResultSchema,
  runParamsSchema,
  runResultSchema,
  subscribeEventsParamsSchema,
  subscribeEventsResultSchema,
  unsubscribeEventsParamsSchema,
  unsubscribeEventsResultSchema,
  permissionRespondParamsSchema,
  permissionRespondResultSchema,
  setModelParamsSchema,
  setModelResultSchema,
  getModelsParamsSchema,
  getModelsResultSchema,
  compactParamsSchema,
  compactResultSchema,
  readFileParamsSchema,
  readFileResultSchema,
  searchTextParamsSchema,
  searchTextResultSchema,
  findFilesParamsSchema,
  findFilesResultSchema,
  configureToolsParamsSchema,
  configureToolsResultSchema,
  type HarnessMethodName,
  type HarnessModelSelection,
  type ListSessionsParams,
  type ListSessionsResult,
  type HarnessSessionSummary,
  type CreateSessionParams,
  type CreateSessionResult,
  type AttachSessionParams,
  type AttachSessionResult,
  type DetachSessionParams,
  type DetachSessionResult,
  type ForkSessionParams,
  type ForkSessionResult,
  type RewindSessionParams,
  type RewindSessionResult,
  type SendMessageParams,
  type SendMessageResult,
  type CancelTurnParams,
  type CancelTurnResult,
  type RunParams,
  type RunResult,
  type SubscribeEventsParams,
  type SubscribeEventsResult,
  type UnsubscribeEventsParams,
  type PermissionRespondParams,
  type PermissionRespondResult,
  type SetModelParams,
  type GetModelsParams,
  type GetModelsResult,
  type CompactParams,
  type CompactResult,
  type ReadFileParams,
  type ReadFileResult,
  type SearchTextParams,
  type SearchTextResult,
  type FindFilesParams,
  type FindFilesResult,
  type ConfigureToolsParams,
  type ConfigureToolsResult,
} from "./methods.js";
