/**
 * @acode/dynamic-workflow 执行引擎核心的模块导出。
 */

export { WorkflowEngine, type EngineConfig, type RunSettlement } from "./engine.js";
export { InMemoryJournalStore } from "./journal-memory.js";
export {
  ConcurrencyController,
  CONCURRENCY_DECREASE_FACTOR,
  CONCURRENCY_FLOOR,
  CONCURRENCY_IDLE_RESET_MS,
  CONCURRENCY_INCREASE_AFTER_SUCCESSES,
  CONCURRENCY_INCREASE_STEP,
  type ConcurrencyControllerSnapshot,
  type ConcurrencyThrottleReason,
} from "./concurrency.js";
export { canonicalJson, fnv1a, inputHash } from "./hash.js";
// 结构化错误的运行时 guard 与预算明细类型直接从 errors.ts 导出（types.ts 已抵 400 行门，
// 而这两者是 errors.ts 自己的表面；WorkflowError 本体按惯例仍经 types.js 再导出）。
export { isWorkflowErrorCode, type AgentBudgetDetails } from "./errors.js";
export {
  WorkflowError,
  INSTRUCTIONS_HEAD_MAX_CHARS,
  LAST_TOOL_NAME_MAX_CHARS,
  LAST_TOOL_TARGET_MAX_CHARS,
  NUDGE_ATTEMPTS,
  REPAIR_ATTEMPTS,
  refToString,
  type ActorId,
  type ActorRecord,
  type ActorRef,
  type ActorSessionSeed,
  type ArtifactPublishRequest,
  type ArtifactRef,
  type ArtifactVersionRecord,
  type AskMessage,
  type AskLastTool,
  type AskProgress,
  type AskSpec,
  type AskStats,
  type AskWaitInfo,
  type ConcurrencyChange,
  type ConcurrencyChangeReason,
  type Caps,
  type InstanceRef,
  type JournalStorePort,
  type ImportedActorCandidate,
  type ImportedAskEntry,
  type ImportedInFlightAsk,
  type ImportedRunCache,
  type ImportedWorldEntry,
  type ListEventsOptions,
  type NodeKind,
  type NodeOutcome,
  type NodeRecord,
  type NodeRecordStatus,
  type WorldReadInput,
  WORLD_READ_INPUT_MAX_BYTES,
  type PersonaSpec,
  type RunEvent,
  type RunRecord,
  type RunSettlementRecord,
  type RunStallInfo,
  type RunStatus,
  type RunStopReason,
  type SessionRef,
  type StoredEvent,
  type SubmitVerdict,
  type ValidateFn,
  type WorkflowDriver,
  type WorkflowErrorCode,
  type WorkflowErrorJson,
  type ProviderStopDetails,
  type WorkflowErrorMismatch,
  type WorkflowHostApi,
  type WorkflowReportSink,
  type WorldReadOp,
} from "./types.js";
